### ISSUE TITLE
Support for PHP7

### ISSUE THREAD

**Issue by legendtang** [sergeychernyshev/showslow#116]
When execute `make`, it shows:

```
Submodule path 'users': checked out 'd4175fd7b13be2a7b3ed66e64788a0ebd9306154'
# generating crc32 hashes of all assets that should be versioned
find ./ -type f | grep -v -E '^./(blog|tools|timeline|timeplot|ajax|users|svn-assets|flot\/examples)/' | grep -E '\.(png|jpg|js|gif|ico)$' | sort | xargs -n10 php crc32.php | sed -e 's/\t\.\//\t/' > asset_versions.tsv
# uncomment next line when we'll have any CSS files to process
find ./ -name '*.css' -not -wholename "./timeplot/*" -not -wholename "./timeline/*" -not -wholename "./ajax/*" -not -wholename "./users/*" -not -wholename "./blog/*" -not -wholename "./tools/*" | xargs -n1 php svn-assets/cssurlrewrite.php
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/douyudev/showslow/global.php:1155
Stack trace:
#0 /home/douyudev/showslow/svn-assets-config.php(2): require_once()
#1 /home/douyudev/showslow/svn-assets/config.php(5): require_once('/home/douyudev/...')
#2 /home/douyudev/showslow/svn-assets/cssurlrewrite.php(3): require_once('/home/douyudev/...')
#3 {main}
  thrown in /home/douyudev/showslow/global.php on line 1155
xargs: php: exited with status 255; aborting
Makefile:76: recipe for target 'assets' failed
make: *** [assets] Error 124
```

Obviously, it is `mysql_connect()` that has been removed in PHP7. Should use mysqli or PDO instead. Consider it an enhancement?

**Comment by sergeychernyshev** [comment]
Yeah, that's a good point. StartupAPI uses mysqli already so it might be a relatively easy change. Want to make a pull request?
